@host = http://localhost:5000

### Add New Employee
POST {{host}}/api/employees 
Content-Type: application/json

{
  "personalInfo": {
    "firstName": "John",
    "lastName": "Doe",
    "dateOfBirth": "1990-01-01",
    "gender": "male",
    "maritalStatus": "single",
    "nationality": "American",
    "phone": "+1 123-456-7890",
    "emergencyContact": {
      "name": "Jane Doe",
      "relationship": "Sister",
      "phone": "+1 321-654-0987"
    }
  },
  "address": {
    "street": "123 Main St",
    "city": "New York",
    "state": "NY",
    "zipCode": "10001",
    "country": "USA"
  },
  "jobInfo": {
    "department": "68771b06525d6fa9ee5025e0", 
    "position": "Software Engineer",
    "employmentType": "full-time",
    "joinDate": "2025-07-16",
    "workLocation": "office"
  },
  "salary": {
    "baseSalary": 800,
    "currency": "USD",
    "payFrequency": "monthly"
  },
  "benefits": {
    "healthInsurance": true,
    "dentalInsurance": false,
    "visionInsurance": true,
    "retirement401k": true
  },
  "userInfo": {
    "email": "john.doe@example.com",
    "password": "securePass123",
    "role": "employee"
  }
}


